<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="10" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1339" started-at="2019-04-04T12:29:12Z" finished-at="2019-04-04T12:29:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1339" started-at="2019-04-04T12:29:12Z" finished-at="2019-04-04T12:29:14Z">
      <class name="TestScript.Bill">
        <test-method status="PASS" signature="TS01_Sales()[pri:0, instance:TestScript.Bill@2752f6e2]" name="TS01_Sales" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Sales" finished-at="2019-04-04T12:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS01_Sales -->
        <test-method status="PASS" signature="TS02_Checkout()[pri:0, instance:TestScript.Bill@2752f6e2]" name="TS02_Checkout" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Checkout Cart" finished-at="2019-04-04T12:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS02_Checkout -->
        <test-method status="FAIL" signature="TS03_SelectMode()[pri:0, instance:TestScript.Bill@2752f6e2]" name="TS03_SelectMode" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Select Mode" finished-at="2019-04-04T12:29:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at TestScript.Bill.TS03_SelectMode(Bill.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS03_SelectMode -->
        <test-method status="PASS" signature="TS04_Payment()[pri:0, instance:TestScript.Bill@2752f6e2]" name="TS04_Payment" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Pay credit card" finished-at="2019-04-04T12:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS04_Payment -->
        <test-method status="FAIL" signature="TS05_Logout()[pri:0, instance:TestScript.Bill@2752f6e2]" name="TS05_Logout" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Logout" finished-at="2019-04-04T12:29:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at TestScript.Bill.TS05_Logout(Bill.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS05_Logout -->
      </class> <!-- TestScript.Bill -->
      <class name="TestScript.Sales">
        <test-method status="PASS" signature="TS01_Login()[pri:0, instance:TestScript.Sales@2d209079]" name="TS01_Login" duration-ms="5" started-at="2019-04-04T12:29:12Z" description="Login" finished-at="2019-04-04T12:29:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS01_Login -->
        <test-method status="PASS" signature="TS02_Search()[pri:0, instance:TestScript.Sales@2d209079]" name="TS02_Search" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Search for flights" finished-at="2019-04-04T12:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS02_Search -->
        <test-method status="PASS" signature="TS03_Select()[pri:0, instance:TestScript.Sales@2d209079]" name="TS03_Select" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Select flight" finished-at="2019-04-04T12:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS03_Select -->
        <test-method status="PASS" signature="TS04_Book()[pri:0, instance:TestScript.Sales@2d209079]" name="TS04_Book" duration-ms="0" started-at="2019-04-04T12:29:13Z" description="Book flight" finished-at="2019-04-04T12:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS04_Book -->
        <test-method status="FAIL" signature="TS05_AddCart()[pri:0, instance:TestScript.Sales@2d209079]" name="TS05_AddCart" duration-ms="1" started-at="2019-04-04T12:29:13Z" description="Add to Cart" finished-at="2019-04-04T12:29:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at TestScript.Sales.TS05_AddCart(Sales.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS05_AddCart -->
      </class> <!-- TestScript.Sales -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
